/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shiftModule_28 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] result
  );
  
  
  
  always @* begin
    result = 1'h0;
    
    case (alufn)
      6'h20: begin
        result = a << b[0+2-:3];
      end
      6'h21: begin
        result = a >> b[0+2-:3];
      end
      6'h23: begin
        result = $signed(a) >>> b[0+2-:3];
      end
    endcase
  end
endmodule
