/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compareModule_27 (
    input [15:0] a,
    input [15:0] b,
    input [7:0] alufn,
    output reg [15:0] result
  );
  
  
  
  integer v;
  
  wire [16-1:0] M_adderModule_result;
  reg [16-1:0] M_adderModule_a;
  reg [16-1:0] M_adderModule_b;
  reg [6-1:0] M_adderModule_alufn;
  adderModule_25 adderModule (
    .a(M_adderModule_a),
    .b(M_adderModule_b),
    .alufn(M_adderModule_alufn),
    .result(M_adderModule_result)
  );
  
  always @* begin
    result = 1'h0;
    M_adderModule_a = a;
    M_adderModule_b = b;
    M_adderModule_alufn = 6'h01;
    v = a[15+0-:1] && b[15+0-:1] && !M_adderModule_result[15+0-:1] || !a[15+0-:1] && b[15+0-:1] && M_adderModule_result[15+0-:1];
    
    case (alufn)
      6'h33: begin
        result[0+0-:1] = a == b;
      end
      6'h35: begin
        result[0+0-:1] = M_adderModule_result[15+0-:1] ^ v;
      end
      6'h37: begin
        result[0+0-:1] = (a == b) || (M_adderModule_result[15+0-:1] ^ v);
      end
    endcase
  end
endmodule
